// @flow

import * as React from 'react';
import type { PreferencesValues } from '../MainFrame/Preferences/PreferencesContext';
import Authentication from '../Utils/AirStudioServices/Authentication';
import AuthenticatedUserContext from './AuthenticatedUserContext';
import type { AuthenticatedUser } from './AuthenticatedUserContext';

type Props = {|
  authentication: Authentication,
  preferencesValues: PreferencesValues,
  children: React.Node,
|};

const makeMockAuthenticatedUser = (
  authentication: Authentication
): AuthenticatedUser => ({
  authenticated: true,
  firebaseUser: null,
  profile: {
    id: 'guest',
    email: 'guest@airstudio.local',
    username: 'Guest',
    description: null,
    updatedAt: Date.now(),
    createdAt: Date.now(),
    getGameStatsEmail: false,
    getNewsletterEmail: false,
    appLanguage: 'en',
    isCreator: true,
    isPlayer: false,
    isEmailAutogenerated: true,
    donateLink: null,
    discordUsername: null,
  },
  loginState: 'done',
  creatingOrLoggingInAccount: false,
  badges: [],
  cloudProjects: [],
  cloudProjectsFetchingErrorLabel: null,
  receivedAssetPacks: [],
  receivedAssetShortHeaders: [],
  receivedGameTemplates: [],
  receivedBundles: [],
  gameTemplatePurchases: [],
  assetPackPurchases: [],
  coursePurchases: [],
  bundlePurchases: [],
  recommendations: [],
  notifications: [],
  userEarningsBalance: null,
  limits: null,
  authenticationError: null,
  usages: null,
  subscription: null,
  subscriptionPricingSystem: null,
  onLogin: async () => {},
  onLoginWithProvider: async () => {},
  onCancelLoginOrSignUp: () => {},
  onLogout: async () => {},
  onCreateAccount: async () => {},
  onEditProfile: async () => {},
  onResetPassword: async () => {},
  onOpenLoginDialog: () => {},
  onOpenLoginWithPurchaseClaimDialog: () => {},
  onOpenEditProfileDialog: () => {},
  onOpenChangeEmailDialog: () => {},
  onOpenCreateAccountDialog: () => {},
  onOpenCreateAccountWithPurchaseClaimDialog: () => {},
  onOpenPurchaseClaimDialog: () => {},
  claimedProductOptions: null,
  onClosePurchaseClaimDialog: () => {},
  onBadgesChanged: async () => {},
  onCloudProjectsChanged: async () => {},
  onRefreshUserProfile: async () => {},
  onRefreshFirebaseProfile: async () => {},
  onRefreshSubscription: async () => {},
  onRefreshLimits: async () => {},
  onRefreshGameTemplatePurchases: async () => {},
  onRefreshAssetPackPurchases: async () => {},
  onRefreshCoursePurchases: async () => {},
  onRefreshBundlePurchases: async () => {},
  onRefreshEarningsBalance: async () => {},
  onRefreshNotifications: async () => {},
  onPurchaseSuccessful: async () => {},
  onSendEmailVerification: async () => {},
  onOpenEmailVerificationDialog: () => {},
  onAcceptGameStatsEmail: async () => {},
  getAuthorizationHeader: () => authentication.getAuthorizationHeader(),
  onEmailVerificationSent: () => {},
  onLoginWithRedirectResult: async () => {},
});

const AuthenticatedUserProvider = ({
  authentication,
  preferencesValues,
  children,
}: Props) => {
  const authenticatedUser = makeMockAuthenticatedUser(authentication);

  return (
    <AuthenticatedUserContext.Provider value={authenticatedUser}>
      {children}
    </AuthenticatedUserContext.Provider>
  );
};

export default AuthenticatedUserProvider;
