// @flow
import type { LoginProvider } from '../../LoginProvider';
import { type CommunityLinks, type UserSurvey } from './User';

export type Profile = {|
  id: string,
  email: string,
  username: ?string,
  description: ?string,
  updatedAt: number,
  createdAt: number,
  deactivatedAt?: number,
  getGameStatsEmail: boolean,
  getNewsletterEmail: boolean,
  appLanguage: ?string,
  isCreator: boolean,
  isPlayer: boolean,
  isEmailAutogenerated: boolean,
  donateLink: ?string,
  discordUsername: ?string,
  githubUsername?: ?string,
  fullName?: ?string,
  communityLinks?: CommunityLinks,
  survey?: UserSurvey,
  teamOrCompanySize?: string,
  companyName?: string,
  creationExperience?: string,
  creationGoal?: string,
  hearFrom?: string,
|};

export type LoginForm = {|
  email: string,
  password: string,
|};

export type ForgotPasswordForm = {|
  email: string,
|};

export type RegisterForm = {|
  email: string,
  password: string,
  username: string,
  getNewsletterEmail: boolean,
|};

export type ChangeEmailForm = {|
  email: string,
|};

export type AuthError = {
  code:
    | 'auth/invalid-email'
    | 'auth/missing-email'
    | 'auth/user-disabled'
    | 'auth/user-not-found'
    | 'auth/wrong-password'
    | 'auth/email-already-in-use'
    | 'auth/operation-not-allowed'
    | 'auth/weak-password'
    | 'auth/username-used'
    | 'auth/malformed-username'
    | 'auth/requires-recent-login'
    | 'auth/too-many-requests'
    | 'auth/internal-error'
    | 'auth/network-request-failed'
    | 'auth/account-exists-with-different-credential',
};

export type UpdateGitHubStarResponse = {|
  +code:
    | 'github-star/badge-already-given'
    | 'github-star/badge-given'
    | 'github-star/repository-not-starred'
    | 'github-star/user-not-found',
|};

export type UpdateTiktokFollowResponse = {|
  +code:
    | 'tiktok-follow/badge-already-given'
    | 'tiktok-follow/badge-given'
    | 'tiktok-follow/account-not-followed'
    | 'tiktok-follow/user-not-found',
|};

export type UpdateTwitterFollowResponse = {|
  +code:
    | 'twitter-follow/badge-already-given'
    | 'twitter-follow/badge-given'
    | 'twitter-follow/account-not-followed'
    | 'twitter-follow/user-not-found',
|};

export type UpdateYoutubeSubscriptionResponse = {|
  +code:
    | 'youtube-subscription/badge-already-given'
    | 'youtube-subscription/badge-given'
    | 'youtube-subscription/channel-not-subscribed'
    | 'youtube-subscription/user-not-found',
|};

export type IdentityProvider = 'google' | 'apple' | 'github';

const guestFirebaseUser = {
  uid: 'guest-user-id',
  email: 'guest@airstudio.local',
  emailVerified: true,
  isAnonymous: true,
  displayName: 'Guest',
  photoURL: null,
  reload: () => Promise.resolve(),
  getIdToken: () => Promise.resolve('guest-token'),
  getIdTokenResult: () => Promise.resolve({ token: 'guest-token', signInProvider: 'anonymous', expirationTime: '', issuedAtTime: '', authTime: '', claims: {} }),
  phoneNumber: null,
  providerData: [],
  providerId: 'anonymous',
  metadata: { creationTime: Date.now().toString(), lastSignInTime: Date.now().toString() },
  delete: () => Promise.resolve(),
  toJSON: () => ({}),
  refreshToken: 'guest',
  tenantId: null,
};

export default class Authentication {
  auth: { currentUser: typeof guestFirebaseUser };
  _onUserLogoutCallbacks: Array<() => void | Promise<void>> = [];
  _onUserUpdateCallbacks: Array<() => void | Promise<void>> = [];
  loginProvider: ?LoginProvider;
  _initialAuthCheckPromise: Promise<void>;

  constructor() {
    this.auth = { currentUser: guestFirebaseUser };
    this._initialAuthCheckPromise = Promise.resolve();
  }

  setLoginProvider = (loginProvider: LoginProvider) => {
    this.loginProvider = loginProvider;
  };

  addUserLogoutListener = (cb: () => void | Promise<void>) => {
    this._onUserLogoutCallbacks.push(cb);
  };

  addUserUpdateListener = (cb: () => void | Promise<void>) => {
    this._onUserUpdateCallbacks.push(cb);
  };

  removeEventListener = (cbToRemove: () => void | Promise<void>) => {
    this._onUserLogoutCallbacks = this._onUserLogoutCallbacks.filter(
      cb => cb !== cbToRemove
    );
    this._onUserUpdateCallbacks = this._onUserUpdateCallbacks.filter(
      cb => cb !== cbToRemove
    );
  };

  createFirebaseAccount = (form: RegisterForm): Promise<void> => {
    return Promise.resolve();
  };

  createUser = (
    getAuthorizationHeader: () => Promise<string>,
    form: RegisterForm,
    appLanguage: string
  ): Promise<void> => {
    return Promise.resolve();
  };

  login = (form: LoginForm): Promise<void> => {
    return Promise.resolve();
  };

  loginWithProvider = ({
    provider,
    signal,
  }: {|
    provider: IdentityProvider,
    signal?: AbortSignal,
  |}): Promise<void> => {
    return Promise.resolve();
  };

  forgotPassword = (form: ForgotPasswordForm): Promise<void> => {
    return Promise.resolve();
  };

  getFirebaseUser = async (): Promise<any> => {
    return guestFirebaseUser;
  };

  sendFirebaseEmailVerification = async (): Promise<void> => {
    return;
  };

  changeEmail = async (
    getAuthorizationHeader: () => Promise<string>,
    form: ChangeEmailForm
  ): any => {
    return;
  };

  getUserProfile = async (
    getAuthorizationHeader: () => Promise<string>
  ): Promise<Profile> => {
    return {
      id: 'guest-user-id',
      email: 'guest@airstudio.local',
      username: 'Guest',
      description: null,
      updatedAt: Date.now(),
      createdAt: Date.now(),
      getGameStatsEmail: false,
      getNewsletterEmail: false,
      appLanguage: 'en',
      isCreator: true,
      isPlayer: false,
      isEmailAutogenerated: true,
      donateLink: null,
      discordUsername: null,
    };
  };

  updateGitHubStar = async (
    getAuthorizationHeader: () => Promise<string>
  ): Promise<UpdateGitHubStarResponse> => {
    return { code: 'github-star/badge-given' };
  };

  updateTiktokFollow = async (
    getAuthorizationHeader: () => Promise<string>
  ): Promise<UpdateTiktokFollowResponse> => {
    return { code: 'tiktok-follow/badge-given' };
  };

  updateTwitterFollow = async (
    getAuthorizationHeader: () => Promise<string>
  ): Promise<UpdateTwitterFollowResponse> => {
    return { code: 'twitter-follow/badge-given' };
  };

  updateYoutubeSubscription = async (
    getAuthorizationHeader: () => Promise<string>
  ): Promise<UpdateYoutubeSubscriptionResponse> => {
    return { code: 'youtube-subscription/badge-given' };
  };

  acceptGameStatsEmail = async (
    getAuthorizationHeader: () => Promise<string>,
    value: boolean
  ): any => {
    return;
  };

  getFirebaseUserSync = (): any => {
    return guestFirebaseUser;
  };

  logout = async (): Promise<void> => {
    return;
  };

  deleteAccount = async (
    getAuthorizationHeader: () => Promise<string>
  ): Promise<void> => {
    return;
  };

  getAuthorizationHeader = async (): Promise<string> => {
    return 'Bearer guest-token';
  };

  isAuthenticated = (): boolean => {
    return true;
  };

  waitForInitialAuthCheck = (): Promise<void> => {
    return this._initialAuthCheckPromise;
  };
}
